
### Posts

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?sender=677d55ec97bfc1da0b095c5f

###

GET http://localhost:3000/posts/677d566297bfc1da0b095c66

###

POST http://localhost:3000/posts 
Content-Type: application/json

{
    "title": "title", "sender": "677d55ec97bfc1da0b095c5f", "content": "Shachar Shemesh"
}


### Comments

GET http://localhost:3000/comments

###

GET http://localhost:3000/comments/67404e9c77e68352216905e2

###

GET http://localhost:3000/comments/byPostId/67403fe268c4ec19bd0a54d5


###

POST http://localhost:3000/comments 
Content-Type: application/json

{ 
    "postId": "67403fe268c4ec19bd0a54d5", "content": "test", "user": "avi" 
}

###

DELETE http://localhost:3000/comments/674051574498b6d40b76377a

###

PUT http://localhost:3000/comments/674051574498b6d40b76377a 
Content-Type: application/json

{
    "username": "shachar",
    "password": "123",
    "email": "shachar@gmail.com"
}

###
