
###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?sender=677d55ec97bfc1da0b095c5f

###

GET http://localhost:3000/posts/677d566297bfc1da0b095c66

###

POST http://localhost:3000/posts 
Content-Type: application/json

{
    "title": "title", "sender": "677d55ec97bfc1da0b095c5f", "content": "Shachar Shemesh"
}

######################### Comments

GET http://localhost:3000/comments

###


GET http://localhost:3000/comments?user=677d549ebd23a5c623143a64

###

GET http://localhost:3000/comments/677d554ebd23a5c623143a6e

###

GET http://localhost:3000/comments/post/674051584498b6d40b763782


###

POST http://localhost:3000/comments 
Content-Type: application/json

{
    "post": "674051584498b6d40b763782", "content": "first1", "user": "677d549ebd23a5c623143a64"
}

###

DELETE http://localhost:3000/comments/674051584498b6d40b763780

###

PUT http://localhost:3000/comments/674051584498b6d40b763782 
Content-Type: application/json

{
    "post": "674051584498b6d40b763782", "content": "first", "user": "677d549ebd23a5c623143a64"
}

### Users

GET http://localhost:3000/users


###

GET http://localhost:3000/users/677d55ec97bfc1da0b095c5f

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "shachar",
    "password": "123",
    "email": "shacharsms10@gmail.com"
}

###

PUT http://localhost:3000/users/677d55ec97bfc1da0b095c5f
Content-Type: application/json

{
    "username": "shachar",
    "password": "123",
    "email": "shachar@gmail.com"
}

###
